"""
tests/vybz/test_skill_v2.py

Unit tests for the AgentSkills.io (v2) implementation in Skill.
Verifies directory-based loading, metadata validation, and resource aggregation.

Relies on fixtures generated by: scripts/generate_skill_v2_fixtures.sh
"""
import pytest
from pathlib import Path
from vybz.skill import Skill

@pytest.fixture
def skills_v2_root():
    """
    Resolves the root directory of the v2 test fixtures.
    Assumes the test is running from the project root or the file location.
    """
    # Locate tests/fixtures/skills_v2 relative to this test file
    # tests/vybz/test_skill_v2.py -> parents[1] is tests/ -> fixtures/skills_v2
    root = Path(__file__).parent.parent / "fixtures" / "skills_v2"
    if not root.exists():
        pytest.fail(f"Test fixtures not found at {root}. Run scripts/generate_skill_v2_fixtures.sh first.")
    return root

class TestSkillV2Loading:
    """
    Tests the factory method Skill.from_directory().
    """

    def test_from_directory_valid(self, skills_v2_root):
        """
        Happy Path: Verify loading a fully compliant skill.
        """
        # Arrange
        skill_path = skills_v2_root / "valid-skill"

        # Act
        skill = Skill.from_directory(skill_path)

        # Assert
        assert skill.id == "valid-skill"
        assert skill.name == "valid-skill"
        assert "compliant skill" in skill.description
        assert skill.path == skill_path
        # Check that the body was loaded
        assert "primary instruction block" in skill.instructions

    def test_from_directory_name_mismatch(self, skills_v2_root):
        """
        Spec Violation: Verify ValueError is raised if YAML name != Directory name.
        """
        # Arrange
        skill_path = skills_v2_root / "mismatched-skill"

        # Act & Assert
        with pytest.raises(ValueError) as exc:
            Skill.from_directory(skill_path)
        
        assert "must match directory name" in str(exc.value)

    def test_from_directory_broken_yaml(self, skills_v2_root):
        """
        Sad Path: Verify parser handles malformed YAML gracefully (raises ValueError).
        """
        # Arrange
        skill_path = skills_v2_root / "broken-yaml-skill"

        # Act & Assert
        with pytest.raises(ValueError) as exc:
            Skill.from_directory(skill_path)
        
        assert "Failed to parse YAML" in str(exc.value)

    def test_from_directory_missing_file(self, skills_v2_root):
        """
        Sad Path: Verify FileNotFoundError if SKILL.md is missing.
        """
        # Arrange
        skill_path = skills_v2_root / "ghost-skill"

        # Act & Assert
        with pytest.raises(FileNotFoundError):
            Skill.from_directory(skill_path)

    def test_nested_content_aggregation(self, skills_v2_root):
        """
        Feature: Verify that markdown files in subdirectories are aggregated
        into the main instructions.
        """
        # Arrange
        skill_path = skills_v2_root / "nested-skill"

        # Act
        skill = Skill.from_directory(skill_path)

        # Assert
        # 1. Root content present?
        assert "Root Instructions" in skill.instructions
        # 2. Nested content present?
        assert "Advanced Details" in skill.instructions
        # 3. Structural Header present?
        # Note: The relative path logic in _crawl_subdirectories handles OS separators
        assert "advanced/details.md" in skill.instructions or "advanced\\details.md" in skill.instructions


class TestSkillV2Rendering:
    """
    Tests the render() method for v2 skills, focusing on resource discovery.
    """

    def test_render_includes_instructions(self, skills_v2_root):
        """Verify the rendered string contains the main body."""
        skill = Skill.from_directory(skills_v2_root / "valid-skill")
        output = skill.render()
        
        assert "#### valid-skill" in output
        assert "primary instruction block" in output

    def test_render_discovers_scripts(self, skills_v2_root):
        """Verify that scripts/ directory contents are listed in the prompt."""
        skill = Skill.from_directory(skills_v2_root / "valid-skill")
        output = skill.render()

        assert "**Available Scripts:**" in output
        assert "utils.py" in output

    def test_render_aggregates_nested_markdown(self, skills_v2_root):
        """
        Verify that the render output (via instructions) includes the content
        of nested markdown files, effectively flattening the knowledge base.
        """
        skill = Skill.from_directory(skills_v2_root / "nested-skill")
        output = skill.render()

        # The render method just outputs self.instructions for v2
        # So we verify the aggregation logic held up
        assert "### advanced/details.md" in output or "### advanced\\details.md" in output
        assert "This content should be appended" in output
